import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    //width: 393,
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 110,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  heroheader: {
    //width: 393,
    height: 139,
    padding: 40,
    paddingTop: 40,
    paddingRight: 24,
    paddingBottom: 40,
    paddingLeft: 24,
    gap: 16,
    backgroundColor: '#FAFBFB',
  },
  modifica: {
    width: 151,
    height: 22,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'left',
  },
  puoi: {
    width: 345,
    height: 21,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#4D4D4D',
  },
  body: {
    height: 541,
    backgroundColor: '#FFFFFF',
  },
  list: {
    width: 393,
    height: 541,
    padding: 24,
    justifyContent: 'space-between',
  },
  personaldatacard: {
    width: 345,
    height: 67,
    padding: 16,
    borderRadius: 16,
  },
  titles: {
    width: 237,
    height: 35,
  },
  email: {
    width: 61,
    height: 13,
    fontFamily: 'Caros',
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 13,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
  },
  personalframe: {
    width: 195,
    height: 22,
    gap: 4,
    flexDirection: 'row',
  },
  natalias: {
    width: 128,
    height: 22,
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 20,
    textAlign: 'center',
    color: '#2C2D2E',
    right: 20,
  },

  frames: {
    width: 345,
    height: 40,
    padding: 0,
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    borderRadius: 8,
    gap: 10,
    backgroundColor: '#3C75FB',
    marginTop: 230,
  },
  modi: {
    width: 300,
    height: 25,
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    color: '#FAFBFB',
    paddingTop: 6,
  },
});
