import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    //width: 393,
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  logo: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 120,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  hero: {
    //width: 393,
    height: 150,
    padding: 14,
    paddingTop: 14,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 24,
    borderRadius: 0,
    borderTopStartRadius: 0,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    gap: 10,
    backgroundColor: '#12208A',
  },
  cards: {
    width: 361,
    height: 120,
    padding: 24,
    paddingTop: 24,
    paddingRight: 12,
    paddingBottom: 24,
    paddingLeft: 12,
    borderRadius: 20,
    //border: 0.25,
    gap: 10,
    backgroundColor: '#ffffff',
  },
  bodys: {
    width: 337,
    height: 80,
  },
  content: {
    width: 329,
    height: 80,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 0,
    paddingLeft: 24,
    gap: 10,
  },
  Nats: {
    width: 234,
    height: 34,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 28,
    fontWeight: '300',
    lineHeight: 34,
    letterSpacing: 0,
    textAlign: 'left',
    left: 30,
  },
  ipsum: {
    width: 281,
    height: 36,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '300',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#7F7F7F',
  },
  body: {
    width: 393,
    height: 507,
  },
  container: {
    width: 393,
    height: 438,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    gap: 16,
  },
  inputgroup: {
    width: 361,
    height: 46,
    borderRadius: 16,
    //border: 0.25,
    backgroundColor: '#FFFFFF',
  },
  inputelement: {
    width: 361,
    height: 54,
    padding: 4,
    paddingTop: 4,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    gap: 2,
  },
  inputslot: {
    width: 361,
    height: 46,
    padding: 12,
    borderRadius: 12,
    gap: 10,
    flexDirection: 'row',
  },
  search: {
    width: 16,
    height: 16,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 17,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ADB3BD',
  },
  cerca: {
    width: 62,
    height: 22,
    color: '#ADB3BD',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 17,
    letterSpacing: 0,
    textAlign: 'left',
  },
  arrow: {
    width: 14,
    height: 16,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ADB3BD',
    left: 210,
  },
  cardscontainer: {
    width: 361,
    height: 384,
    gap: 8,
  },
  cardframe: {
    width: 361,
    height: 211,
    gap: 35,
    left: 10,
    flexDirection: 'row',
  },
  cardone: {
    width: 146,
    height: 149,
    padding: 12,
    borderRadius: 16,
    //border: 0.25,
    backgroundColor: '#2057B8',
  },
  images: {
    width: 120,
    height: 100,
    borderRadius: 8,
    gap: 10,
  },
  code: {
    width: 122,
    height: 26,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 36,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#FAFBFB',
  },
  cardtwo: {
    width: 146,
    height: 149,
    padding: 12,
    borderRadius: 16,
    //border: 0.25,
    gap: 16,
    backgroundColor: '#FFFFFF',
  },
  menuitem: {
    width: 90,
    height: 90,
    padding: 16,
    borderRadius: 60,
    gap: 10,
    backgroundColor: '#2A3DAA',
    left: 10,
  },
  icons: {
    width: 40,
    height: 40,
    left: 10,
    top: 10,
    fontSize: 40,
    fontWeight: '900',
    lineHeight: 40,
    letterSpacing: 0,
    textAlign: 'center',
  },
  my: {
    width: 95,
    height: 25,
    bottom: 10,
    fontFamily: 'Caros',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'center',
    left: 10,
    color: '#2C2D2E',
  },
  cardthree: {
    width: 361,
    height: 105,
    padding: 12,
    borderRadius: 16,
    //border: 0.25,
    gap: 16,
    backgroundColor: '#FFFFFF',
    bottom: 60,
  },
  illustration: {
    width: 92,
    height: 89,
    gap: 8,
  },
  install: {
    width: 59,
    height: 59,
    left: 150,
  },
  installion: {
    width: 64,
    height: 18,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    left: 150,
  },
});
