import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 100,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  body: {
    width: 393,
    height: 680,
    borderRadius: 16,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    gap: 8,
  },
  installationcard: {
    width: 361,
    height: 109,
    gap: 8,
  },
  frameone: {
    width: 361,
    height: 109,
    padding: 24,
    borderRadius: 16,
    //border: 0.25,
    gap: 16,
    backgroundColor: 'rgba(42, 61, 170, 1)', // #2A3DAA
    elevation: 4, // Android shadow
    shadowColor: '#4D4D4D',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.14,
    shadowRadius: 1,
    flexDirection: 'row',
  },
  frametitle: {
    width: 211,
    height: 61,
    gap: 12,
  },
  titleone: {
    width: 95,
    height: 20,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.10000000149011612,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  secondtitle: {
    width: 111,
    height: 41,
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -1.600000023841858,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  frametitle2: {
    width: 86,
    height: 61,
    gap: 12,
  },
  secondtitletwo: {
    width: 86,
    height: 20,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.10000000149011612,
    textAlign: 'left',
    color: '#FFFFFF',
  },
  number: {
    width: 40,
    height: 41,
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -1.600000023841858,
    textAlign: 'center',
  },
  card: {
    width: 361,
    height: 133,
    gap: 8,
  },
  frametwo: {
    width: 361,
    height: 109,
    padding: 24,
    borderRadius: 16,
    //border: 0.25,
    gap: 16,
    backgroundColor: '#009B7A',
    elevation: 4, // Android shadow
    shadowColor: '#4D4D4D',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.14,
    shadowRadius: 1,
    flexDirection: 'row',
  },
  thridtitle: {
    width: 172,
    height: 41,
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -1.600000023841858,
    textAlign: 'center',
  },
  loonarhero: {
    width: 393,
    height: 141,
    paddingTop: 10,
    //marginTop: 105,
    left: 5,
    paddingBottom: 14,
    gap: 4,
  },
  loonarcard: {
    width: 361,
    height: 123,
    padding: 16,
    paddingTop: 16,
    paddingRight: 24,
    paddingBottom: 16,
    paddingLeft: 24,
    borderRadius: 16,
    borderBottomWidth: 0.25,
    gap: 4,
    backgroundColor: '#2A3DAA',
  },
  loonartitle: {
    width: 313,
    height: 41,
    flexDirection: 'row',
  },
  loonartext: {
    width: 111,
    height: 41,
    color: '#FFFFFF',
    fontFamily: 'Caros',
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -1.600000023841858,
    textAlign: 'center',
  },
  modalContainer: {
    // flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: '#FAFBFB',
  },

  inputgroup: {
    width: 321,
    height: 46,
    borderRadius: 16,
    //border: 0.25,
    backgroundColor: '#FFFFFF',
  },
  inputelement: {
    width: 351,
    height: 54,
    padding: 4,
    paddingTop: 4,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    gap: 2,
  },
  inputslot: {
    width: 351,
    height: 46,
    padding: 12,
    borderRadius: 12,
    gap: 10,
    flexDirection: 'row',
  },
  search: {
    width: 16,
    height: 16,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 17,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ADB3BD',
  },
  cerca: {
    width: 62,
    height: 22,
    color: '#ADB3BD',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 17,
    letterSpacing: 0,
    textAlign: 'left',
  },
  arrow: {
    width: 14,
    height: 16,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#ADB3BD',
    left: 180,
  },

  loonarcardcontainer: {
    width: 393,
    height: 509,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  loonarcardone: {
    width: 361,
    height: 132,
    padding: 16,
    paddingTop: 16,
    paddingRight: 8,
    paddingBottom: 16,
    paddingLeft: 16,
    gap: 16,
    backgroundColor: '#FFFFFF',
  },
  loonarcardlogo: {
    width: 100,
    height: 100,
    borderRadius: 24,
    gap: 10,
  },
  imageone: {
    width: 90.25,
    height: 90.25,
    top: -6.12,
    left: -6.6,
  },
  logoimg: {
    width: 100,
    height: 100,
    flexDirection: 'row',
  },
  description: {
    width: 171,
    height: 100,
    gap: 4,
  },
  loonarmain: {
    width: 171,
    height: 71,
  },
  loonarunit: {
    width: 171,
    height: 25,
    gap: 8,
  },
  loonartexts: {
    width: 122,
    height: 25,
    fontFamily: 'Caros',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'center',
    color: '#2C2D2E',
  },
  loonarrole: {
    width: 171,
    height: 18,
    gap: 8,
    flexDirection: 'row',
  },
  loonaruser: {
    width: 12,
    height: 11,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
    left: 5,
  },
  loonarusers: {
    width: 26,
    height: 18,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'left',
    left: 2,
    color: '#0046EA',
  },
  loonarcaption: {
    width: 104,
    height: 28,
  },
  loonarultimo: {
    width: 90,
    height: 14,
    fontFamily: 'Caros',
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
    left: 5,
  },
  loonarNov: {
    width: 104,
    height: 14,
    fontFamily: 'Caros',
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
    left: 3,
  },
  loonartags: {
    width: 171,
    height: 20,
    gap: 8,
  },
  loonarbadge: {
    width: 39,
    height: 19,
    padding: 2,
    paddingTop: 2,
    paddingRight: 12,
    paddingBottom: 2,
    paddingLeft: 12,
    borderRadius: 16,
    gap: 16,
    backgroundColor: '#F3F7FF',
    flexDirection: 'row',
  },
  loonarbell: {
    width: 12,
    height: 11,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
  },
  loonarbades: {
    width: 100,
    height: 16,
    paddingRight: 12,
    paddingLeft: 12,
    borderRadius: 16,
    gap: 10,
    backgroundColor: '#F3F7FF',
  },
  lorem: {
    width: 76,
    height: 16,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#020E4F',
  },
  CTA: {
    width: 34,
    height: 100,
    paddingTop: 40,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 16,
    gap: 10,
  },
  loonarangle: {
    width: 10,
    height: 16,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'center',
  },
  loonartexttwo: {
    width: 152,
    height: 25,
    fontFamily: 'Caros',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'center',
    color: '#2C2D2E',
  },
  loonarsupplier: {
    width: 48,
    height: 18,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 12,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#0046EA',
  },
  loonarclose: {
    left: 170,
    paddingTop: 10,
  },
});
