import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 140,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  body: {
    height: 112.84,
    padding: 40,
    paddingTop: 40,
    paddingRight: 24,
    paddingBottom: 40,
    paddingLeft: 24,
    gap: 24,
    backgroundColor: '#FAFBFB',
  },
  illustration: {
    width: 92,
    height: 89,
    gap: 8,
    flexDirection: 'row',
  },
  savetime: {
    width: 92,
    height: 89,
  },
  text: {
    width: 229,
    height: 41,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#4D4D4D',
  },
  bodycontainer: {
    height: 567.16,
    backgroundColor: '#FFFFFF',
  },
  list: {
    width: 393,
    height: 567.16,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 0,
    paddingLeft: 24,
  },
  notificationlist: {
    width: 345,
    height: 567.16,
    padding: 24,
    paddingTop: 24,
    paddingRight: 8,
    paddingBottom: 24,
    paddingLeft: 8,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  notifica: {
    width: 329,
    height: 79,
    padding: 16,
    paddingTop: 16,
    paddingRight: 0,
    paddingBottom: 16,
    paddingLeft: 0,
    gap: 5,
    color: '#000000',
    borderStyle: 'solid',
    borderBottomWidth: 0.25,
    borderColor: ' #000000',
    marginBottom: 5,
  },
  belltitle: {
    width: 329,
    height: 21,
    gap: 10,
  },
  form: {
    width: 329,
    height: 21,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: 0.02,
    textAlign: 'left',
    color: '#4D4D4D',
  },
  belldati: {
    width: 329,
    height: 21,
    justifyContent: 'space-between',
  },
  frame455: {
    width: 56,
    height: 21,
    gap: 4,
  },
  iconright: {
    width: 20,
    height: 16,
    gap: 10,
    flexDirection: 'row',
  },
  clockicon: {
    width: 16,
    height: 16,
    fontFamily: 'Font Awesome 6 Free',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#999999',
  },
  times: {
    width: 32,
    height: 21,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '300',
    lineHeight: 16,
    letterSpacing: 0.02,
    textAlign: 'left',
    color: '#4D4D4D',
  },
  dates: {
    width: 115,
    height: 21,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '300',
    lineHeight: 16,
    letterSpacing: 0.02,
    textAlign: 'left',
    color: '#4D4D4D',
    left: 30,
  },
  stato: {
    width: 81,
    height: 21,
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#4D4D4D',
    left: 30,
  },
});
