import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 110,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  heroheader: {
    height: 159,
    padding: 40,
    paddingTop: 40,
    paddingRight: 24,
    paddingBottom: 40,
    paddingLeft: 24,
    gap: 16,
    backgroundColor: '#FAFBFB',
  },
  auth: {
    width: 154,
    height: 22,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'left',
  },
  scegli: {
    width: 345,
    height: 41,
    fontFamily: 'Caros',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0.20000000298023224,
    textAlign: 'left',
    color: '#787878',
  },
  body: {
    height: 521,
    backgroundColor: '#FFFFFF',
  },
  list: {
    width: 393,
    height: 521,
    padding: 24,
    justifyContent: 'space-between',
  },
  frame27127: {
    width: 345,
    height: 473,
    gap: 8,
  },
  PersonalDataCardOne: {
    width: 345,
    height: 54,
    padding: 16,
    borderRadius: 16,
    borderBottomWidth: 0.25,
    borderColor: '#4D4D4D33',
    borderStyle: 'solid',
    backgroundColor: '#FFFFFF',
  },
  frame27126: {
    width: 313,
    height: 22,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  auths: {
    width: 172,
    height: 22,
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#2C2D2E',
  },
  righticon: {
    width: 20,
    height: 16,
    gap: 10,
  },
  toggle: {
    width: 18,
    height: 18,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#999999',
  },
  other: {
    width: 108,
    height: 22,
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#2C2D2E',
  },
});
