import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 140,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  hero: {
    height: 206,
    padding: 0,
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 145,
    borderRadius: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    gap: 16,
    backgroundColor: '#12208A',
  },
  avatar: {
    width: 361,
    height: 206,
    gap: 10,
  },
  avatarframe: {
    width: 120,
    height: 120,
    gap: 10,
  },
  images: {
    width: 120,
    height: 120,
  },
  // kyc: {
  //   width: 65.29,
  //   height: 24,
  //   padding: 4,
  //   paddingTop: 4,
  //   paddingRight: 12,
  //   paddingBottom: 4,
  //   paddingLeft: 12,
  //   borderRadius: 20,
  //   gap: 16,
  //   backgroundColor: '#3C4CA7',
  //   left: 100,
  // },
  // kycframe: {
  //   width: 41.29,
  //   height: 16,
  //   gap: 8,
  // },
  avatartitle: {
    width: 361,
    height: 70,
    gap: 8,
  },
  username: {
    width: 228,
    height: 34,
    color: '#FFFFFF',
    fontFamily: 'Caros',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 34,
    letterSpacing: 0,
    textAlign: 'center',
    right: 45,
  },
  body: {
    width: 393,
    height: 457,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    gap: 8,
  },
  nav: {
    width: 361,
    height: 24,
    gap: 24,
    flexDirection: 'row',
  },
  dati: {
    width: 107,
    height: 24,
    padding: 4,
    paddingTop: 4,
    paddingRight: 12,
    paddingBottom: 4,
    paddingLeft: 12,
    borderRadius: 16,
    gap: 16,
    backgroundColor: '#B4C7FB42',
  },
  datipersonali: {
    width: 83,
    height: 16,
    color: '#020E4F',
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
  },
  pre: {
    width: 63,
    height: 24,
    padding: 4,
    paddingTop: 4,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    borderRadius: 16,
    gap: 16,
  },
  preferenze: {
    width: 63,
    height: 16,
    color: '#798294',
    fontFamily: 'Caros',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
  },
  content: {
    width: 361,
    height: 377,
  },
  cards: {
    width: 361,
    height: 377,
    padding: 10,
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    gap: 8,
  },
  personaldatacardone: {
    width: 361,
    height: 57,
    padding: 10,
    borderRadius: 16,
    justifyContent: 'space-between',
    color: '#4D4D4D33',
  },
  personaldatatitle: {
    width: 237,
    height: 35,
  },
  Nome: {
    width: 107,
    height: 13,
    fontFamily: 'Caros',
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 13,
    letterSpacing: 0.20000000298023224,
    textAlign: 'center',
    color: '#798294',
  },
  personalframe: {
    width: 151,
    height: 22,
    gap: 4,
    flexDirection: 'row',
  },
  natalia: {
    width: 127,
    height: 22,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
  },
  email: {
    width: 36,
    height: 22,
  },
  natalias: {
    width: 171,
    height: 22,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'center',
  },
  password: {
    width: 64,
    height: 22,
  },
  dots: {
    width: 128,
    height: 22,
  },
  personaldatacardtwo: {
    width: 361,
    height: 67,
    padding: 10,
    borderRadius: 16,
    //border: 0.25,
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
  },
  editicon: {
    fontWeight: '900',
    fontSize: 16,
    lineHeight: 16,
    textAlign: 'right',
    width: 16,
    height: 16,
    left: 95,
    color: '#2A3DAA',
  },
  editicons: {
    fontWeight: '900',
    fontSize: 16,
    lineHeight: 16,
    textAlign: 'right',
    width: 16,
    height: 16,
    left: 140,
    color: '#2A3DAA',
  },
});
