import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  // InstallingScreen: {
  //   width: 393,
  //   height: 852,
  //   top: 630,
  //   left: 1711.47,
  // },
  header: {
    //width: 393,
    height: 104,
    padding: 0,
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#12208A',
  },
  title: {
    width: 305,
    height: 25,
    flexDirection: 'row',
    marginTop: 60,
  },
  install: {
    width: 115,
    height: 25,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 25,
    letterSpacing: -0.4000000059604645,
    textAlign: 'left',
    left: 140,
  },
  notification: {
    left: 210,
    width: 40,
    height: 41,
    padding: 3,
  },
  body: {
    width: 393,
    height: 680,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    gap: 8,
  },
  cardsone: {
    width: 361,
    height: 22,
    gap: 8,
  },
  textone: {
    width: 135,
    height: 22,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#2C2D2E',
  },
  cardstwo: {
    width: 361,
    height: 24,
    gap: 8,
  },
  cardsframe: {
    width: 62,
    height: 24,
    borderRadius: 16,
    padding: 4,
    paddingTop: 4,
    paddingRight: 12,
    paddingBottom: 4,
    paddingLeft: 12,
    gap: 16,
    backgroundColor: '#B4C7FB42',
  },
  texttwo: {
    width: 38,
    height: 16,
    color: '#020E4F',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0,
    textAlign: 'left',
  },
  cardsthree: {
    width: 361,
    height: 584,
    gap: 8,
  },
  walletcard1: {
    width: 361,
    height: 145,
    padding: 24,
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    borderRadius: 16,
    //border: 0.25,
    backgroundColor: '#FFFFFF',
  },
  frameone: {
    width: 329,
    height: 80,
    gap: 12,
    flexDirection: 'row',
  },
  imagetoken1: {
    width: 64,
    height: 80,
    gap: 10,
  },
  tokencoin1: {
    width: 64,
    height: 64,
  },
  frameonetitle: {
    width: 253,
    height: 68,
  },
  crutoken: {
    width: 120,
    height: 14,
    color: '#2C2D2E',
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: 'center',
  },
  disponibile: {
    width: 67,
    height: 13,
    color: '#798294',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
    letterSpacing: 0,
    textAlign: 'center',
  },
  availabletoken: {
    width: 253,
    height: 41,
    gap: 8,
  },
  inputcard: {
    width: 253,
    height: 36,
    padding: 4,
    paddingTop: 4,
    paddingBottom: 8,
    paddingRight: 4,
    paddingLeft: 8,
    borderRadius: 4,
    gap: 10,
    backgroundColor: '#3F70EE1A',
    flexDirection: 'row',
  },
  cru: {
    width: 67,
    height: 41,
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 41,
    letterSpacing: -1.600000023841858,
    textAlign: 'center',
    color: '#2C2D2E',
  },
  eye: {
    width: 30,
    height: 19,
    color: '#2A3DAA',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 20,
    letterSpacing: 0,
    textAlign: 'center',
    left: 120,
    paddingTop: 3,
  },
  frametwotitle: {
    width: 329,
    height: 37,
    padding: 0,
    paddingTop: 0,
    paddingBottom: 8,
    paddingRight: 0,
    gap: 8,
    flexDirection: 'row',
  },
  crutitle: {
    width: 119,
    height: 37,
    gap: 2,
  },
  legend: {
    width: 111,
    height: 14,
    gap: 4,
    flexDirection: 'row',
  },
  comprato: {
    width: 63,
    height: 13,
    color: '#798294',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
    letterSpacing: 0,
    textAlign: 'center',
  },
  badge: {
    width: 44,
    height: 14,
    padding: 0,
    paddingTop: 0,
    paddingBottom: 4,
    paddingRight: 0,
    paddingLeft: 4,
    borderRadius: 4,
  },
  onchain: {
    width: 36,
    height: 14,
    fontFamily: 'Caros',
    fontSize: 9,
    fontWeight: '600',
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#798294',
  },
  numberscru: {
    width: 114,
    height: 21,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 21,
    letterSpacing: -0.4000000059604645,
    textAlign: 'center',
  },
  crutitles: {
    width: 119,
    height: 37,
    padding: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 8,
    gap: 2,
  },
  legends: {
    width: 97,
    height: 14,
    gap: 4,
    flexDirection: 'row',
  },
  stacked: {
    width: 49,
    height: 13,
    color: '#798294',
    fontFamily: 'Caros',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
    letterSpacing: 0,
    textAlign: 'center',
  },
  untb: {
    width: 169,
    height: 14,
    color: '#2C2D2E',
    fontFamily: 'Caros',
    fontSize: 10,
    fontWeight: '400',
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: 'center',
  },
});
